### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by ThorsAvenger** [micro-ROS/micro_ros_vitis_component#4]
Hi, 
I am experiencing some difficulties installing the micro-ros library for Vitis. I am running a clean install of Ubuntu 24.04 with ROS2 Jazzy and Vitis 2023.2, I pulled the vitis component repository and sourced the Vitis path. I am getting the following error:
```
cp: cannot stat 'microros_build_microblaze_64/microros/install/include/*': No such file or directory
Creating libmicroros.a
find: 'install/lib': No such file or directory
```

Any suggestions on what I am doing wrong here?

**Comment by pablogs9** [comment]
Hello, Jazzy is not currently supported in micro-ROS. We plan to add support during next month.

**Comment by ThorsAvenger** [comment]
HI,
That's too bad, but thank you. Now, I went back to Ubuntu 22.04, installed Humble, Vitis 2023.2 and pulled the repo, but I still get the same error. So could you elaborate a bit more on how or what steps you make to build the library? It seems straight forward enough, but for me it isn't working.

**Comment by pablogs9** [comment]
Which steps are you following?

**Comment by ThorsAvenger** [comment]
The steps from the ReadMe: 
- installed the necessary pip libs
- installed rsync
- Exported the Path
- Execute the .sh script for the VITIS_MICROBLAZE_64 target 
I see now that there are not files or folders not being found: 
```
./build_micro_ros_library.sh: line 185: microros_build_microblaze_64/dev/install/local_setup.sh: No such file or directory
./build_micro_ros_library.sh: line 195: colcon: command not found
Fixing include paths for micro-ROS packages
./build_micro_ros_library.sh: line 212: colcon: command not found
find: ‘./install/include’: No such file or directory
cp: cannot stat 'microros_build_microblaze_64/microros/install/include/*': No such file or directory
Creating libmicroros.a
find: ‘install/lib’: No such file or directory
```

**Comment by pablogs9** [comment]
I guess that the error is: `./build_micro_ros_library.sh: line 195: colcon: command not found` don't you think so?

Are you sure that `pip3 install colcon-common-extensions` is working correctly?

**Comment by ThorsAvenger** [comment]
It is defaulting to user installation because normal site-packages is not writeable, but otherwise the the requirement is already satisfied, letting me believe that it is installed. I can also do python3 -c "import colcon", without getting any errors.

**Comment by pablogs9** [comment]
Can you run `colcon` command?

**Comment by ThorsAvenger** [comment]
I can. It started building. Looks like I needed to reboot the system for some changes to take effect. I'll close the issue if it completes building. Thanks a lot for the guidance!

**Comment by ThorsAvenger** [comment]
Looks like build succesfully, still having some troubles importing it in the Vitis IDE, but that's probalby something different. Once again, thanks for the help
